### ISSUE TITLE
Question on Cross-Validation

### ISSUE THREAD

**Issue by rd1886** [Nixtla/nixtla#253]
Hi,

I have a couple of questions regarding the implementation of cross-validation:

1.  Is it necessary to perform cross-validation with multiple models, or can it be effectively done with just a single model?

2. Are cross-validation and sliding window the same thing in the context of your implementation of cross-validation?

Thanks!

**Comment by elephaint** [comment]
Hi, from [our tutorial on cross validation](https://nixtlaverse.nixtla.io/neuralforecast/examples/cross_validation_tutorial.html):

_Time series cross-validation is a method for evaluating how a model would have performed on historical data. It works by defining a sliding window across past observations and predicting the period following it. It differs from standard cross-validation by maintaining the chronological order of the data instead of randomly splitting it._

Now, to answer your questions:
1. No, you don't need to perform cross-validation with multiple models. See the text above.
2. It's not 'the same thing', i.e. sliding window is a technique we use for cross-validation for time series. See the text above.

Hope this helps.

**Comment by rd1886** [comment]
Thank you for the clarification. How can I do sliding window in Neuralforecast?

**Comment by elephaint** [comment]
Not sure I understand the question. What do you want to do? 

If you want to do cross-validation for a model (which makes use of the sliding window technique), see  [our getting started page on cross validation with NeuralForecast](https://nixtlaverse.nixtla.io/neuralforecast/examples/cross_validation_tutorial.html).

**Comment by rd1886** [comment]
My apologies for the confusion. The cross-validation described in the document is exactly what I was looking for. Thank you!
